name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        preset: [Switch-Release]
    runs-on: ${{ matrix.os }}
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake --preset ${{ matrix.preset }}

    - name: Build
      run: cmake --build --preset ${{ matrix.preset }} --parallel 1

    # only deploy on push
    - name: Deploy
      if: ${{ github.event_name != 'pull_request' && github.event.action != 'unassigned' }}
      uses: actions/upload-artifact@master
      with:
        name: melondDS-${{ matrix.preset }}
        path: build/Switch-${{ matrix.preset }}/*.nro
